# NumPy and Pandas Tutorial
## HODP Bootcamp Week 3
### February 27, 2019

## Some Python refreshers . . . 
- datatypes (strings, integers)
- functions
- data structures like lists and dictionaries

In [2]:
lst = [1, "Emma", 5.0, {"name": "Emma", "age": 20}]

In [3]:
lst[0]

1

In [4]:
lst[-1]

{'name': 'Emma', 'age': 20}

In [4]:
lst[-1]['age']

20

In [5]:
for key in lst[-1].keys():
    print(key)
    print(lst[-1][key])

name
Emma
age
20


## This week:
* Learn how to use Python libraries numpy and pandas to make data analysis easy and efficient
* Understand key differences between Python, NumPy, Pandas
* Practice your new data science skills!

## Getting Started

In [3]:
import numpy as np
import pandas as pd

## Python vs. NumPy
* Python lists are flexible, but bugs can be tough to find and for-loops to manipulate data can be slow
* NumPy arrays have fixed types and functions can be __vectorized__ and operations can be __broadcast__ across arrays

In [23]:
lst = ["Emma", "Jeffrey", "Sahana", 1, 2] # This is a valid Python list
lst

['Emma', 'Jeffrey', 'Sahana', 1, 2]

In [24]:
np_lst = np.array(lst) # Numpy forces them all to be strings
np_lst # Anyone know what this dtype refers to?

array(['Emma', 'Jeffrey', 'Sahana', '1', '2'], dtype='<U7')

In [28]:
for elt in lst:
    print(str(elt) + " 4")

Emma 4
Jeffrey 4
Sahana 4
1 4
2 4


In [29]:
for elt in np_lst:
    print(elt + " is studying abroad")

Emma is studying abroad
Jeffrey is studying abroad
Sahana is studying abroad
1 is studying abroad
2 is studying abroad


## Creating NumPy arrays

First, we can use ``np.array`` to create arrays from Python lists:

In [30]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type.
If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [31]:
np.array([3.14, 4, 2, 3]) # Notice how the elements in the resulting array are all floats

array([3.14, 4.  , 2.  , 3.  ])

In [32]:
np.array([1, 2, 3, 4], dtype='float32') # You can explicitly set the type with the dtype keyword

array([1., 2., 3., 4.], dtype=float32)

Numpy has a bunch of handy built-in functions to generate arrays:

In [33]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [51]:
# Create an array by specifying start and stop values and the spacing between values
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [54]:
# Create a matrix filled with a specific value
np.full((2, 4), 9.9)

array([[9.9, 9.9, 9.9, 9.9],
       [9.9, 9.9, 9.9, 9.9]])

In [60]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

We can slice NumPy arrays and index into them using bracket notation:

In [40]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
array[0, 1]

1

In [23]:
array[:, 2]

array([2, 5, 8])

In [42]:
array[1, :]

array([3, 4, 5])

## Rule of Thumb: Don't reinvent the wheel
Google if a function already exists that does what you want

## So, how is this useful for data analysis?

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question.
Perhaps the most common summary statistics are the __mean__ and __standard deviation__, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.

In [46]:
big_array = np.random.rand(1000000)

# -n 10 means run it 10 times
%timeit -n 10 sum(big_array)
%timeit -n 10 np.sum(big_array)

150 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
377 µs ± 46.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Some more handy features of NumPy:

One common type of aggregation operation is an aggregate along a row or column.

Say you have some data stored in a two-dimensional array:

In [47]:
M = np.random.random((3, 4))
print(M)

[[0.04552443 0.68499213 0.3775258  0.72626632]
 [0.79273573 0.30434285 0.76995745 0.61946326]
 [0.74113299 0.55422022 0.55550509 0.91396659]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

In [48]:
M.min()

0.04552443322388455

But what if you want the min for each row or each column?

In [49]:
# min of each column
M.min(axis=0)

array([0.04552443, 0.30434285, 0.3775258 , 0.61946326])

In [50]:
# min of each row
M.min(axis=1)

array([0.04552443, 0.30434285, 0.55422022])

### Other aggregation functions

Most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values, which are marked by the special floating-point ``NaN`` value.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |
| ``np.concatenate``| N/A                 | Concatenate arrays (without manual copying!)  |

## Pandas

* Pandas is another useful library for data analysis.
* While NumPy is really useful for math, it relies on __arrays__ of specific datatypes (ints, floats, etc).
* Pandas uses two data structures: `Series` and `DataFrame` that are designed to package lots of different types of data similar to a spreadsheet.
* It combines the functionality of Python and NumPy with the ease of use of Google Sheets.

In [4]:
# Creating and summarizing a data frame

states = pd.DataFrame({'State':['Massachusetts','Ohio','Alaska','California','Arkansas'],
                     'Population Rank':[15, 7, 48, 1, 33]})
states

State  Population Rank
0  Massachusetts               15
1           Ohio                7
2         Alaska               48
3     California                1
4       Arkansas               33

In [5]:
states.describe()

Population Rank
count         5.000000
mean         20.800000
std          19.395876
min           1.000000
25%           7.000000
50%          15.000000
75%          33.000000
max          48.000000

## Example: House Rankings

We will:
1. Read in the data
2. Manipulate the data into a more useable form
3. Analyze the data
4. Plot our results

### Reading in the data

It's super easy to use Pandas to read in data from csv files:

In [6]:
rankings = pd.read_csv("house_rankings_2019.csv")
rankings.head()

House   1   2   3   4   5   6   7   8   9  10  11  12
0        Adams   7  14  19  19  30  20  19  19  24   7  12  13
1        Cabot   0   3   5   3   7   1   9   8  15  39  52  61
2      Dunster  11  22  45  29  16  25  17  14  10   4   7   3
3  Pforzheimer   3   6   7   6   9  11   8  17  26  61  35  14
4     Winthrop  27  91  23  19  12   7   4   8   3   3   1   5

And it looks beautiful:

In [7]:
rankings.set_index("House", inplace=True)
rankings

1   2   3   4   5   6   7   8   9  10  11  12
House                                                       
Adams          7  14  19  19  30  20  19  19  24   7  12  13
Cabot          0   3   5   3   7   1   9   8  15  39  52  61
Dunster       11  22  45  29  16  25  17  14  10   4   7   3
Pforzheimer    3   6   7   6   9  11   8  17  26  61  35  14
Winthrop      27  91  23  19  12   7   4   8   3   3   1   5
Kirkland       5   5  11  23  20  30  25  28  20   9  12  15
Quincy         5   8  26  29  30  28  27  22  13   5   5   5
Lowell       118  28  19  12   6  10   4   2   3   1   0   0
Mather         9   6   5  16  19   8  19  24  45  21   8  23
Eliot         15  12  28  32  28  24  21  17   8   8   8   2
Leverett       3   5  12  13  21  30  44  35  15   7  10   8
Currier        0   3   3   2   5   9   6   9  21  38  53  54

### Manipulating the data

It may be useful to also have this data in a NumPy array so we can use some of the NumPy aggregate functions to analyze our data (although Pandas also has its own version of these functions).  It's easy to convert between types:

In [41]:
rankings.values

array([[ 20,  15,  24,  38,  37,  44,  67,  75,  74,  28,  32,  80],
       [  5,  13,  16,  17,   7,  20,  16,  31,  49, 118, 148,  94],
       [ 19,  19,  35,  50,  71,  63,  72,  70,  56,  24,  24,  31],
       [ 17,  15,  19,  25,  27,  40,  44,  67, 112,  37,  55,  76],
       [ 28,  43,  55,  90,  71,  82,  65,  44,  21,  17,  14,   4],
       [ 11,  22,  40,  73,  76,  81,  94,  66,  36,  18,  11,   6],
       [ 45,  67, 113,  56,  70,  42,  44,  52,  19,  10,  11,   5],
       [ 14,  10,  16,  15,  18,  19,  20,  23,  43,  92, 114, 150],
       [ 37,  57,  60,  67,  57,  76,  49,  40,  38,  23,  16,  14],
       [152, 106,  63,  51,  45,  35,  22,  24,  14,   5,   7,  10],
       [ 10,  21,  15,   6,  16,  19,  29,  33,  66, 158,  98,  63],
       [176, 146,  78,  46,  39,  13,  12,   9,   6,   4,   4,   1]])

We can also splice this array to just get the values for the first column or row:

In [42]:
rankings.values[:, 0]

array([ 20,   5,  19,  17,  28,  11,  45,  14,  37, 152,  10, 176])

In [43]:
rankings.values[0, :]

array([20, 15, 24, 38, 37, 44, 67, 75, 74, 28, 32, 80])

We can rename data labels pretty easily:

In [12]:
rankings.rename(index = {'Pforzheimer':'Pfoho'})

1   2   3   4   5   6   7   8   9  10  11  12
House                                                    
Adams       7  14  19  19  30  20  19  19  24   7  12  13
Cabot       0   3   5   3   7   1   9   8  15  39  52  61
Dunster    11  22  45  29  16  25  17  14  10   4   7   3
Pfoho       3   6   7   6   9  11   8  17  26  61  35  14
Winthrop   27  91  23  19  12   7   4   8   3   3   1   5
Kirkland    5   5  11  23  20  30  25  28  20   9  12  15
Quincy      5   8  26  29  30  28  27  22  13   5   5   5
Lowell    118  28  19  12   6  10   4   2   3   1   0   0
Mather      9   6   5  16  19   8  19  24  45  21   8  23
Eliot      15  12  28  32  28  24  21  17   8   8   8   2
Leverett    3   5  12  13  21  30  44  35  15   7  10   8
Currier     0   3   3   2   5   9   6   9  21  38  53  54

### Analyzing the data

In [77]:
rankings.describe() # This is not super insightful

1          2          3          4          5          6  \
count   12.000000  12.000000  12.000000  12.000000  12.000000  12.000000   
mean    16.916667  16.916667  16.916667  16.916667  16.916667  16.916667   
std     32.701010  24.603985  12.339577  10.184287   9.258493  10.299676   
min      0.000000   3.000000   3.000000   2.000000   5.000000   1.000000   
25%      3.000000   5.000000   6.500000  10.500000   8.500000   8.750000   
50%      6.000000   7.000000  15.500000  17.500000  17.500000  15.500000   
75%     12.000000  16.000000  23.750000  24.500000  22.750000  25.750000   
max    118.000000  91.000000  45.000000  32.000000  30.000000  30.000000   

               7          8          9         10         11         12  
count  12.000000  12.000000  12.000000  12.000000  12.000000  12.000000  
mean   16.916667  16.916667  16.916667  16.916667  16.916667  16.916667  
std    11.758620   9.452833  11.618624  19.038040  18.817102  20.110867  
min     4.000000   2.000000   3.000000   1.000000   0.000000   0.000000  
25%     7.500000   8.750000   9.500000   4.750000   6.500000   4.500000  
50%    18.000000  17.000000  15.000000   7.500000   9.000000  10.500000  
75%    22.000000  22.500000  21.750000  25.250000  17.750000  17.000000  
max    44.000000  35.000000  45.000000  61.000000  53.000000  61.000000

 #### First, how many students filled out the survey?

In [19]:
n = rankings.sum(axis=1)[0] # Axis=1 specifies analysis along rows, [0] specifies sum of only the first row
print(n)

203


#### Which house was the most popular? The least popular?

In [86]:
rankings.iloc[:, 0].idxmax()
# iloc allows us to extract rows/cols when our data labes aren't [0... n]
# idmax gives us the "index" (data label) of the max value in the column we're lokoing at (first-palce votes)

'Lowell'

In [84]:
rankings.iloc[:, 11].idxmax()

'Cabot'

#### Can we sort by popularity?

In [89]:
rankings.sort_values(by='1',ascending=False)

1   2   3   4   5   6   7   8   9  10  11  12
House                                                       
Lowell       118  28  19  12   6  10   4   2   3   1   0   0
Winthrop      27  91  23  19  12   7   4   8   3   3   1   5
Eliot         15  12  28  32  28  24  21  17   8   8   8   2
Dunster       11  22  45  29  16  25  17  14  10   4   7   3
Mather         9   6   5  16  19   8  19  24  45  21   8  23
Adams          7  14  19  19  30  20  19  19  24   7  12  13
Kirkland       5   5  11  23  20  30  25  28  20   9  12  15
Quincy         5   8  26  29  30  28  27  22  13   5   5   5
Pforzheimer    3   6   7   6   9  11   8  17  26  61  35  14
Leverett       3   5  12  13  21  30  44  35  15   7  10   8
Cabot          0   3   5   3   7   1   9   8  15  39  52  61
Currier        0   3   3   2   5   9   6   9  21  38  53  54

#### How could we make a `DataFrame` with the percentage of first place rankings for each house?

In [49]:
rankings.iloc[:,0] / n * 100

House
Adams           3.745318
Cabot           0.936330
Kirkland        3.558052
Mather          3.183521
Quincy          5.243446
Leverett        2.059925
Dunster         8.426966
Currier         2.621723
Eliot           6.928839
Lowell         28.464419
Pforzheimer     1.872659
Winthrop       32.958801
Name: 1, dtype: float64

#### How could we make a `DataFrame` with the average ranking for each house? 

In [103]:
avg = np.zeros(12)
w_rankings = rankings.copy()
for i in range(0,12):
    w_rankings.iloc[:,i] = rankings.iloc[:,i] * (i+1)
avg_rankings = w_rankings.sum(axis=1) / n
avg_rankings

House
Adams           6.389163
Cabot          10.000000
Dunster         4.975369
Pforzheimer     8.669951
Winthrop        3.330049
Kirkland        6.901478
Quincy          5.812808
Lowell          2.216749
Mather          7.620690
Eliot           5.330049
Leverett        6.822660
Currier         9.931034
dtype: float64

In [104]:
avg_rankings.sort_values()

House
Lowell          2.216749
Winthrop        3.330049
Dunster         4.975369
Eliot           5.330049
Quincy          5.812808
Adams           6.389163
Leverett        6.822660
Kirkland        6.901478
Mather          7.620690
Pforzheimer     8.669951
Currier         9.931034
Cabot          10.000000
dtype: float64